name: rappi-challenge
channels:
  - defaults
dependencies:
  - numpy>=1.14.3
  - pandas>=1.0.0
  - scikit-learn=0.24.2
  - nomkl
  - fsspec
  - lightgbm
  - urllib3
  - mlflow
  - pyarrow
  - psutil
  - matplotlib
